version: '3'
services:
  ethereum-node:
    image: ${DOCKER_IMAGE}
    hostname: ${HOST_NAME}-d
    restart: always
    environment:
      - WS_SECRET=${WS_SECRET}
    ports:
      - "3000:3000"
      - "3001:3001"
